sonar.projectKey=eyewear-system
sonar.projectName=Eyewear System
sonar.projectVersion=1.0
sonar.sources=backend,frontend
sonar.exclusions=backend/PHPMailer/**,frontend/assets/images/**,backend/scratch/**,backend/tests/**
sonar.sourceEncoding=UTF-8
# sonar.php.coverage.reportPaths=backend/tests/coverage.xml
